import ExcalidrawModel
import Foundation
import XCTest
@testable import ExcalidrawCollab

/// The cross-language guarantee: the Swift client decodes the shared protocol
/// fixtures (generated by the TypeScript `@cyberdynecorpai/protocol` `canonicalEncode`) and
/// re-encodes byte-identical JSON. If the wire formats ever diverge, this fails
/// — so an iOS device and the web client are proven to speak the same protocol.
final class WireConformanceTests: XCTestCase {
    private static let names = [
        "join", "leave", "room-state", "peer-joined", "peer-left",
        "presence", "pointer", "element-updates", "scene-snapshot", "ping", "ack"
    ]

    private func fixture(_ name: String) throws -> String {
        // <root>/Tests/ExcalidrawCollabTests/<thisFile> -> up 3 to <root>.
        let root = URL(fileURLWithPath: "\(#filePath)")
            .deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
        let url = root.appendingPathComponent("Fixtures/protocol/\(name).json")
        return try String(contentsOf: url, encoding: .utf8)
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }

    func testEveryFixtureRoundTripsByteIdentically() throws {
        for name in Self.names {
            let wire = try fixture(name)
            let message = try CollabCodec.decode(wire)
            let reencoded = try CollabCodec.encode(message)
            XCTAssertEqual(reencoded, wire, "wire mismatch for \(name)")
        }
    }

    func testDecodesIntoTheExpectedCases() throws {
        if case let .join(proto, room, peer) = try CollabCodec.decode(fixture("join")) {
            XCTAssertEqual(proto, protocolVersion)
            XCTAssertEqual(room, "room-1")
            XCTAssertEqual(peer.id, "p1")
        } else {
            XCTFail("join did not decode to .join")
        }

        if case let .elementUpdates(elements) = try CollabCodec.decode(fixture("element-updates")) {
            XCTAssertEqual(elements.first?.id, "el-1")
            XCTAssertEqual(elements.first?.base.version, 3)
            XCTAssertEqual(elements.first?.base.versionNonce, 42)
        } else {
            XCTFail("element-updates did not decode")
        }

        if case let .presence(peerId, presence) = try CollabCodec.decode(fixture("presence")) {
            XCTAssertEqual(peerId, "p1")
            XCTAssertEqual(presence.pointer?.x, 12.5)
            XCTAssertEqual(presence.selectedIds, ["el-1"])
        } else {
            XCTFail("presence did not decode")
        }
    }

    func testRejectsUnknownType() {
        XCTAssertThrowsError(try CollabCodec.decode(#"{"type":"explode"}"#))
    }
}
